# Run the checks
name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: check-group-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - run: bun install

      - name: run check
        run: bun check
