# Checks to see if any secrets are being committed to the repository
# A little bit annoying to run yourself, but I don't like worrying about this stuff
name: secrets

on:
  pull_request:
  push:
  workflow_dispatch:

permissions: 
  contents: read 
  id-token: write 
  issues: write 
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: secret scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified
