# Run size-limit
name: size

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: run size-limit
        uses: yuckabug/size-limit-action@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
